### PR TITLE
Add GHA workflow for updating src/

### PR DESCRIPTION
**Pull request by jamessan**
Closes neovim/neovim#14261

### CODE REVIEW

**Comment by justinmk** [comment]
Any particular reason not to have this live in neovim core repo? Hard for outsiders to understand how everything fits together if logic is spread across repos.

**Comment by jamessan** [comment]
Isn't it easier to figure out if the action lives in the repo it's modifying?

**Comment by justinmk** [comment]
Isn't something else doing a push to this repo though? Hence the need for a cron workflow here. I guess whatever pushes to this repo, could also do the followup work being done by the GH action here. And that avoids a bit of maintenance with the extra CI logic here.

**Comment by jamessan** [comment]
No, the cron is what updates this repo.  Each action only modifies the repo it belongs to, rather than having one repo with access to everything.

**Pull request merged**
